import { jsPDF } from 'jspdf';
import { createServerSupabaseClient } from '@/lib/supabase';
import type { Shipment } from '@/types';

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;
    const supabase = createServerSupabaseClient();

    const { data: shipment, error } = await supabase
      .from('shipments')
      .select(`
        *,
        origin_contact:contacts!origin_contact_id(*),
        destination_contact:contacts!destination_contact_id(*),
        carrier:contacts!carrier_id(*)
      `)
      .eq('id', id)
      .single();

    if (error || !shipment) {
      return Response.json({ error: 'Shipment not found' }, { status: 404 });
    }

    const s = shipment as Shipment;
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('FRESHZILLA', 20, 20);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Shipment Document', 20, 28);

    doc.setLineWidth(0.5);
    doc.line(20, 33, 190, 33);

    // Reference & Status
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Reference:', 20, 42);
    doc.setFont('helvetica', 'normal');
    doc.text(s.reference, 65, 42);

    doc.setFont('helvetica', 'bold');
    doc.text('Status:', 20, 50);
    doc.setFont('helvetica', 'normal');
    doc.text(s.status.replace('_', ' ').toUpperCase(), 65, 50);

    doc.setFont('helvetica', 'bold');
    doc.text('Created:', 20, 58);
    doc.setFont('helvetica', 'normal');
    doc.text(new Date(s.created_at).toLocaleDateString(), 65, 58);

    doc.line(20, 64, 190, 64);

    // Route
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Route', 20, 73);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Origin:', 20, 82);
    doc.setFont('helvetica', 'normal');
    const originText = s.origin_contact
      ? `${s.origin_contact.name} — ${s.origin_contact.city}, ${s.origin_contact.country}`
      : 'N/A';
    doc.text(originText, 65, 82);

    doc.setFont('helvetica', 'bold');
    doc.text('Destination:', 20, 90);
    doc.setFont('helvetica', 'normal');
    const destText = s.destination_contact
      ? `${s.destination_contact.name} — ${s.destination_contact.city}, ${s.destination_contact.country}`
      : 'N/A';
    doc.text(destText, 65, 90);

    doc.setFont('helvetica', 'bold');
    doc.text('Carrier:', 20, 98);
    doc.setFont('helvetica', 'normal');
    doc.text(s.carrier ? s.carrier.name : 'N/A', 65, 98);

    doc.line(20, 104, 190, 104);

    // Goods
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Goods Description', 20, 113);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Description:', 20, 122);
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(s.description, 120);
    doc.text(descLines, 65, 122);

    let y = 122 + (descLines.length - 1) * 5 + 8;

    doc.setFont('helvetica', 'bold');
    doc.text('Weight:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(s.weight_kg ? `${s.weight_kg} kg` : 'N/A', 65, y);
    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.text('Volume:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(s.volume_cbm ? `${s.volume_cbm} CBM` : 'N/A', 65, y);
    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.text('Value:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(s.value_usd ? `${s.value_usd} ${s.currency}` : 'N/A', 65, y);
    y += 8;

    if (s.hs_code) {
      doc.setFont('helvetica', 'bold');
      doc.text('HS Code:', 20, y);
      doc.setFont('helvetica', 'normal');
      doc.text(s.hs_code, 65, y);
      y += 8;
    }

    if (s.incoterm) {
      doc.setFont('helvetica', 'bold');
      doc.text('Incoterm:', 20, y);
      doc.setFont('helvetica', 'normal');
      doc.text(s.incoterm, 65, y);
      y += 8;
    }

    if (s.special_handling) {
      doc.setFont('helvetica', 'bold');
      doc.text('Special Handling:', 20, y);
      doc.setFont('helvetica', 'normal');
      const handlingLines = doc.splitTextToSize(s.special_handling, 115);
      doc.text(handlingLines, 65, y);
      y += (handlingLines.length - 1) * 5 + 8;
    }

    // Footer
    doc.setLineWidth(0.3);
    doc.line(20, 275, 190, 275);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120);
    doc.text(`Generated by Freshzilla Supply Chain — ${new Date().toISOString()}`, 20, 281);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    // Log the generation
    await supabase.from('automation_logs').insert({
      event_type: 'pdf_generated',
      shipment_id: id,
      details: { reference: s.reference },
      status: 'success',
    });

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="FZ-${s.reference}.pdf"`,
      },
    });
  } catch (err) {
    return Response.json({ error: String(err) }, { status: 500 });
  }
}
